# Generated by Django 3.1.3 on 2020-11-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20201114_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='year',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, to='matches.iplseason'),
        ),
    ]
