# Generated by Django 3.1.3 on 2020-11-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
    ]
